config/routes.rb
Czanitech::Application.routes.draw do
  resources :myimages do
    get 'show_hidden', :on => :collection
    get 'show_all', :on => :collection
  end

  resources :pymtreceiveds

  resources :pymts

  get "price/index"
  
  resources :projstatuses

  resources :customerchats

  get "allusers", to: 'users#index', as: :allusers
  get "edituser", to: "users#edit", as: :edituser

  resources :movielinks

  resources :sendmessages
  get 'send', to: 'sendmessages#new', as: :send
  get "about/index"
  get "home/index"
  
  resources :scripts

  devise_for :users
  
  devise_scope :user do
      get 'register', to: 'devise/registrations#new', as: :register
      get 'login', to: 'devise/sessions#new', as: :login
      get 'logout', to: 'devise/sessions#destroy', as: :logout
      get 'edit', to: 'devise/registrations#edit', as: :edit
  end

  root :to => "home#index"
  
  







  

end

app/models/customerchat.rb
class Customerchat < ActiveRecord::Base
	belongs_to :scripts
end

app/models/movielink.rb
class Movielink < ActiveRecord::Base

end

app/models/myimage.rb
class Myimage < ActiveRecord::Base
	belongs_to :user
	mount_uploader :image, ImageUploader
end

app/models/projstatus.rb
class Projstatus < ActiveRecord::Base

end

app/models/pymt.rb
class Pymt < ActiveRecord::Base
end

app/models/pymtreceived.rb
class Pymtreceived < ActiveRecord::Base
end

app/models/script.rb
class Script < ActiveRecord::Base

	before_save :concatenate_chat
	belongs_to :user

	def concatenate_chat
		if chat_entry_changed?
		    self.chat_history = "#{usertype} #{chat_entry}<hr>#{chat_history}".html_safe
		    self.chat_entry = ""
		end
	end

	def self.searchproject(search)
		if search
			find(:all, :conditions => ['LOWER(project) LIKE ?', "%#{search.downcase}%"], :order => "created_at DESC")
		else
			find(:all, :order => "created_at DESC")
		end
	end

	def self.searchdescr(search)
		if search
			find(:all, :conditions => ['LOWER(notes) LIKE ?', "%#{search.downcase}%"], :order => "created_at DESC")
		else
			find(:all, :order => "created_at DESC")
		end
	end
	
end

app/models/sendmessage.rb
class Sendmessage < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :scripts
  has_many :myimages

  def full_name 
  	first_name + " " + last_name
  end
  
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pymts_controller.rb
class PymtsController < ApplicationController
  before_action :set_pymt, only: [:show, :edit, :update, :destroy]

  # GET /pymts
  # GET /pymts.json
  def index
    @pymts = Pymt.all.order('order_to_show')
  end

  # GET /pymts/1
  # GET /pymts/1.json
  def show
  end

  # GET /pymts/new
  def new
    @pymt = Pymt.new
  end

  # GET /pymts/1/edit
  def edit
  end

  # POST /pymts
  # POST /pymts.json
  def create
    @pymt = Pymt.new(pymt_params)

    respond_to do |format|
      if @pymt.save
        format.html { redirect_to @pymt, notice: 'Pymt was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pymt }
      else
        format.html { render action: 'new' }
        format.json { render json: @pymt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pymts/1
  # PATCH/PUT /pymts/1.json
  def update
    respond_to do |format|
      if @pymt.update(pymt_params)
        format.html { redirect_to @pymt, notice: 'Pymt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pymt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pymts/1
  # DELETE /pymts/1.json
  def destroy
    @pymt.destroy
    respond_to do |format|
      format.html { redirect_to pymts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pymt
      @pymt = Pymt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pymt_params
      params.require(:pymt).permit(:order_to_show, :pymt_status, :is_requesting_pymt)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(type)
		case type
		when :alert
			"alert-error"
		when :notice
			"alert-success"
		else
			"alert-success"
		end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movielinks_helper.rb
module MovielinksHelper
end

app/helpers/myimages_helper.rb
module MyimagesHelper
end

app/helpers/price_helper.rb
module PriceHelper
end

app/helpers/projstatuses_helper.rb
module ProjstatusesHelper
end

app/helpers/pymts_helper.rb
module PymtsHelper
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/helpers/sendmessages_helper.rb
module SendmessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/pymts/_form.html.erb
<%= form_for(@pymt) do |f| %>
  <% if @pymt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pymt.errors.count, "error") %> prohibited this pymt from being saved:</h2>

      <ul>
      <% @pymt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading"><center>Edit Payment Status</center></div>
      <div class="panel-body">
        <div class="col-md-2">
          <div class="field">
            <%= f.label :order_to_show, "Show Order" %><br>
            <%= f.text_field :order_to_show, :autofocus => true, class: "form-control", :required => true %>
          </div>
        </div>
        <div class="col-md-5">
          <div class="field">
            <%= f.label :pymt_status, "Status Name" %><br>
            <%= f.text_field :pymt_status, class: "form-control", :required => true %>
          </div>
        </div>
        <div class="col-md-2">
          <div class="field">
            <%= f.label :is_requestion_pymt, "Request Money?" %>
            <%= f.check_box :is_requesting_pymt, class: "form-control"%>
            
          </div>
        </div>
        <div class="col-md-3"><center>
          <div class="actions">
            <%= f.label  "Select Option" %><br>
            <%= f.submit "Submit", class: "btn btn-success" %>
            <%= link_to "Cancel", pymts_path, class: "btn btn-danger" %>
          </div></center>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/pymts/edit.html.erb
<%= render 'form' %>

app/views/pymts/index.html.erb
<%= link_to 'Add New Payment Status', new_pymt_path, class: "btn btn-success" %>
<br><br>
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Payment Statuses</div>
  <!-- Table -->
  <table class="table table-striped table-bordered">

    <thead>
      <tr>
        <th>Show Order</th>
        <th>Payment Status Description</th>
        <th>Request Money from Customer</th>
        <th><center>Action</center></th>
      </tr>
    </thead>

    <tbody>
      <% @pymts.each do |pymt| %>
        <tr>
          <td width=10%><%= pymt.order_to_show %></td>
          <td width=50%><%= pymt.pymt_status %></td>
          <td width=20%>
            <% if pymt.is_requesting_pymt %>
              <center><i class="fa fa-thumbs-o-up"></i></center>
            <% end %>
          </td>
          <td width=20% style="text-align:center" >
            <div class="btn-group btn-group-sm">
              <%= link_to 'Edit', edit_pymt_path(pymt), class: "btn btn-success" %>
              <%= link_to ' Delete', pymt, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            </div>
          </td>
        </tr>

      <% end %>
    </tbody>
  </table>

<br>

app/views/pymts/new.html.erb
<%= render 'form' %>

app/views/pymts/show.html.erb
<p>
  <strong>Order to show:</strong>
  <%= @pymt.order_to_show %>
</p>

<p>
  <strong>Pymt status:</strong>
  <%= @pymt.pymt_status %>
</p>

<%= link_to 'Edit', edit_pymt_path(@pymt) %> |
<%= link_to 'Back', pymts_path %>