config/routes.rb
Czanitech::Application.routes.draw do
  resources :myimages do
    get 'show_hidden', :on => :collection
    get 'show_all', :on => :collection
  end

  resources :pymtreceiveds

  resources :pymts

  get "price/index"
  
  resources :projstatuses

  resources :customerchats

  get "allusers", to: 'users#index', as: :allusers
  get "edituser", to: "users#edit", as: :edituser

  resources :movielinks

  resources :sendmessages
  get 'send', to: 'sendmessages#new', as: :send
  get "about/index"
  get "home/index"
  
  resources :scripts

  devise_for :users
  
  devise_scope :user do
      get 'register', to: 'devise/registrations#new', as: :register
      get 'login', to: 'devise/sessions#new', as: :login
      get 'logout', to: 'devise/sessions#destroy', as: :logout
      get 'edit', to: 'devise/registrations#edit', as: :edit
  end

  root :to => "home#index"
  
  







  

end

app/models/customerchat.rb
class Customerchat < ActiveRecord::Base
	belongs_to :scripts
end

app/models/movielink.rb
class Movielink < ActiveRecord::Base

end

app/models/myimage.rb
class Myimage < ActiveRecord::Base
	belongs_to :user
	mount_uploader :image, ImageUploader
end

app/models/projstatus.rb
class Projstatus < ActiveRecord::Base

end

app/models/pymt.rb
class Pymt < ActiveRecord::Base
end

app/models/pymtreceived.rb
class Pymtreceived < ActiveRecord::Base
end

app/models/script.rb
class Script < ActiveRecord::Base

	before_save :concatenate_chat
	belongs_to :user

	def concatenate_chat
		if chat_entry_changed?
		    self.chat_history = "#{usertype} #{chat_entry}<hr>#{chat_history}".html_safe
		    self.chat_entry = ""
		end
	end

	def self.searchproject(search)
		if search
			find(:all, :conditions => ['LOWER(project) LIKE ?', "%#{search.downcase}%"], :order => "created_at DESC")
		else
			find(:all, :order => "created_at DESC")
		end
	end

	def self.searchdescr(search)
		if search
			find(:all, :conditions => ['LOWER(notes) LIKE ?', "%#{search.downcase}%"], :order => "created_at DESC")
		else
			find(:all, :order => "created_at DESC")
		end
	end
	
end

app/models/sendmessage.rb
class Sendmessage < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :scripts
  has_many :myimages

  def full_name 
  	first_name + " " + last_name
  end
  
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_script, only: [:show, :edit, :update, :destroy]

  # GET /scripts
  # GET /scripts.json
  def index
    if current_user.admin?
      if (params[:searchproject]) 
        @scripts = Script.searchproject(params[:searchproject])
      elsif (params[:searchdescr]) 
        @scripts = Script.searchdescr(params[:searchdescr])
      else
        @scripts = Script.order('created_at DESC')
      end
    else
      if (params[:searchproject]) 
        @scripts = current_user.scripts.searchproject(params[:searchproject])
      elsif (params[:searchdescr]) 
        @scripts = current_user.scripts.searchdescr(params[:searchdescr])
      else
        @scripts = current_user.scripts.order('created_at DESC')
      end
    end
    @projstatuses = Projstatus.all 
  end

  # GET /scripts/1
  # GET /scripts/1.json
  def show

  end

  # GET /scripts/new
  def new
    @script = Script.new
    @movielinks = Movielink.all.limit(1)
    @projstatuses = Projstatus.all
    @pymts = Pymt.all
    @myimages = Myimage.all.limit(1)
  end

  # GET /scripts/1/edit
  def edit
    @movielinks = Movielink.all
    @projstatuses = Projstatus.all
    @pymts = Pymt.all
    if current_user.admin?
      @myimages = Myimage.where(image_hidden: [false, nil])
    else
      @myimages = current_user.myimages.where(image_hidden: [false, nil])
    end
  end

  # POST /scripts
  # POST /scripts.json
  def create
    @script = Script.new(script_params)
    @movielinks = Movielink.all.limit(1)

    respond_to do |format|
      if @script.save
        UserMailer.confirmation_message(current_user).deliver
        format.html { redirect_to @script, notice: 'Script was successfully created.' }
        format.json { render action: 'show', status: :created, location: @script }
      else
        format.html { render action: 'new' }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scripts/1
  # PATCH/PUT /scripts/1.json
  def update 
    respond_to do |format|
      if @script.update(script_params)
        format.html { redirect_to edit_script_path(script_params), notice: 'Script was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scripts/1
  # DELETE /scripts/1.json
  def destroy
    @script.destroy
    respond_to do |format|
      format.html { redirect_to scripts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_script
      @script = Script.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def script_params
      params.require(:script).permit(:email, :project, :notes, :step1, :step2, :step3,
       :step4, :step5, :user_id, :movielinkid1, :movielinkid2,
       :chat_history, :chat_entry, :usertype, :status, :pymt_id)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(type)
		case type
		when :alert
			"alert-error"
		when :notice
			"alert-success"
		else
			"alert-success"
		end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movielinks_helper.rb
module MovielinksHelper
end

app/helpers/myimages_helper.rb
module MyimagesHelper
end

app/helpers/price_helper.rb
module PriceHelper
end

app/helpers/projstatuses_helper.rb
module ProjstatusesHelper
end

app/helpers/pymts_helper.rb
module PymtsHelper
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/helpers/sendmessages_helper.rb
module SendmessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/scripts/_form.html.erb
<% tAmount = "" %>
<% hPic = 0 %>
<%= form_for(@script) do |f| %>
  <% if @script.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@script.errors.count, "error") %> prohibited this script from being saved:</h2>
      <ul>
      <% @script.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading"><center><b><%= t('proj_edit.project_script') %></b></center></div>
      <div class="panel-body">
        <div>
          <% if current_user.admin? %>
            <% hPic = 648 %>
            <div class="field">
              <p><b>Customer Id:</b></p>
            </div>
            <div class="form-group">
              <%= f.text_field :user_id, value: @script.user_id, placeholder: "Customer Id", class: "form-control", :required => true %>
            </div>
          <% else %>
            <% hPic = 480 %>
            <%= f.hidden_field :user_id, value: current_user.id %>
          <% end %>
        </div>
        <div class="field">
          <p><b><%= t('proj_edit.name') %></b><br>
            <i><%= t('proj_edit.name_eg') %></i></p>
        </div>
        <div class="field">
          <%= f.text_field :project, :autofocus => true, class: "form-control", :required => true %>
        </div>
      </div>
      <div class="panel-body">
        <div class="field">
          <p><b><%= t('proj_edit.description') %></b><br>
            <i><%= t('proj_edit.description_eg') %></i></p>
        </div>
        <div class="field">
          <%= f.text_area :notes, class: "form-control", :required => true, :rows => 4 %>
        </div>
      </div>
      <div class="panel-body">
        <div class="field">
          <p><b><%= t('proj_edit.step1') %></b><br>
            <i><%= t('proj_edit.step1_eg') %></i></p>
        </div>
        <div class="field">
          <%= f.text_area :step1, class: "form-control", :required => true, :rows => 4 %>
        </div>
      </div>
      <div class="panel-body">
        <div class="field">
          <p><b><%= t('proj_edit.step2') %></b><br>
            <i><%= t('proj_edit.step2_eg') %></i></p>
        </div>
        <div class="field">
          <%= f.text_area :step2, class: "form-control", :required => true, :rows => 4 %>
        </div>
      </div>
      <div class="panel-body">
        <div class="field">
          <p><b><%= t('proj_edit.step3') %></b><br>
            <i><%= t('proj_edit.step3_eg') %></i></p>
        </div>
        <div class="field">
          <%= f.text_area :step3, class: "form-control", :required => true, :rows => 4 %>
        </div>
      </div>
      <div class="panel-body">
        <div class="field">
          <p><b><%= t('proj_edit.step4') %></b><br>
            <i><%= t('proj_edit.step4_eg') %></i></p>
        </div>
        <div class="field">
          <%= f.text_area :step4, class: "form-control", :required => true, :rows => 4 %>
        </div>
      </div>
      <div class="panel-body">
        <div class="field">
          <p><b><%= t('proj_edit.step5') %></b><br>
            <i><%= t('proj_edit.step5_eg').html_safe %></i></p>
        </div>
        <div class="field">
          <%= f.text_area :step5, class: "form-control", :required => true, :rows => 4 %>
          <br><%= f.submit (t('proj_edit.update')), class: "btn btn-success" %>
          <%= link_to (t('proj_edit.cancel')), scripts_path, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <center><b><%= t('proj_edit.other_info') %></b></center>
      </div>
      <div class="panel-body">
        <% if current_user.admin? %>
          <div class="form-group">
            <%= f.collection_select(:pymt_id, Pymt.all.order(:order_to_show), :id, :pymt_status, {:prompt => "Select Payment Status"}, :class => "form-control" ) %>
          </div>
          <div class="form-group">
            <%= f.collection_select(:status, Projstatus.all.order(:ordertoshow), :id, :statusname, {:prompt => "Select Project Status"}, :class => "form-control" ) %>
          </div>
          <div>
            <div class="field col-md-4 row">
              <%= f.text_field :movielinkid1, placeholder: "Movie Id 1", class: "form-control" %>
            </div>
            <div class="field col-md-4">
              <%= f.text_field :movielinkid2, placeholder: "Movie Id 2", class: "form-control" %>
            </div>
            <div class="field col-md-4">
              <%= f.submit "Update", class: "btn btn-success" %>
            </div>
            <br>
          </div>
          <%= f.hidden_field :usertype, value: "<b>Producer:</b><br>" %>
        <% else %>
          <% @pymts.each do |p| %>
            <div>
              <% if p.id == @script.pymt_id %>
                <% tAmount = p.pymt_status %>
                <center> 
                <% if p.is_requesting_pymt %>
                  <div class="alert alert-danger">
                    <b><big><%= p.pymt_status %></big></b>
                  </div>
                  <div>
                    <a href="#openPymt" class="btn btn-danger col-md-12">Pay Now</a><br><br>
                  </div>
                <% else %>
                  <% hPic = 535 %>  
                  <div class="alert alert-success">
                    <b><big><%= p.pymt_status %></big></b>
                  </div>
                <% end %>
                </center>
              <% end %>
            </div>
          <% end %>
          <% @projstatuses.each do |s| %>
            <div>
              <% if s.id == @script.status %>
                <center class="alert alert-warning"> 
                  <b><big><%= s.statusname %></big></b>
                </center>
              <% end %>
            </div>
          <% end %>

          <%= f.hidden_field :usertype, value: "<b>#{current_user.first_name}</b><br>" %>
        <% end %>
        <br>
        <% @movielinks.each do |m| %>
          <div>
            <hr>
            <% if (m.id == @script.movielinkid1) || (m.id == @script.movielinkid2)%>
              <center>      
                <%= m.movielink.to_s.html_safe %>
              </center>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading"><center><b><%= t('proj_edit.messages') %></b></center>
      </div>
      <div class="panel-body">
        <div>
          <%= f.text_area :chat_entry, placeholder: (t('proj_edit.enter_message')), class: "form-control" %><br>
          <%= f.submit (t('proj_edit.submit_comment')), class: "btn btn-success" %>
        </div><br>
        <div class="panel panel-default" style="padding:15px 0px 15px 0px">
          <div class="field col-md-12" style="height:300px; overflow:auto">
            <%= simple_format(@script.chat_history) %>
          </div>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading"><center><b><%= t('proj_edit.my_images') %></b></center>
      </div>
      <div class="panel-body" style="overflow:auto; height:<%= hPic %>px;">
        <div class="row">
          <div class="col-md-12">
            <a href="#uploadFile" class="btn btn-warning col-md-12"><%= t('proj_edit.click_to_manage') %></a> 
          </div>
          <hr>
          <% @myimages.each do |myimage| %>
            <% if myimage.user_id.to_s == @script.user_id.to_s %>
              <center>
                <div class="col-md-12">
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <center><%= myimage.image_name %> - <%= myimage.id %></center>
                    </div>
                    <div class="panel-body" style="height:320px">
                      <div class="field">
                        <div>
                          <%= image_tag myimage.image_url(:thumb).to_s %>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </center>
              <div id="openImage" class="modalDialog">
                <div>
                  <a href="#close" title="Close" class="close">X</a>
                  <%= image_tag myimage.image_url.to_s %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div id="uploadFile" class="modalDialogUpload">
  <div>
    <a href="#close" title="Close" class="close">X</a>
    <div class="col-md-12 row">
      <center>
        <div>
          <h3><%= t('proj_edit.leaving_project')%></h3><br>
          <i style="color:brown"><%= t('proj_edit.if_you_did_not_save')%></i>
          <a href="#close" style="text-decoration:none; color:red"><%= t('proj_edit.cancel')%></a><i style="color:brown"> <%= t('proj_edit.update_before')%></i>
        </div><br>
        <div class="btn-group btn-group-md">
          <%= link_to 'Go to My Images', '/myimages', class: "btn btn-success" %>
        </div>

      </center>
    </div>
  </div>
</div>

<div id="openPymt" class="modalDialog">
  <div>
    <a href="#close" title="Close" class="close">X</a>
    <form role="form" action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" >
        <input type="hidden" name="cmd" value="_s-xclick">
        <input type="hidden" name="hosted_button_id" value="LA58B9YYS3FMJ">
        <input type="hidden" name="on0" value="Video Animation">
        <div class="form-group">
          <h2>Payment Form</h2>
        </div>
        <div class="form-group">
          <label style="color:red"><%= tAmount %></label>
          <select name="os0" class="form-control">
          <option value="With voice over.">With voice over. $399.00 USD</option>
          <option value="Without voice over.">Without voice over. $199.00 USD</option>
          <option value="Extra work">Extra work $50.00 USD</option>
          <option value="Extra work">Extra work $20.00 USD</option>
          <option value="Extra work">Extra work $10.00 USD</option>
          </select>
        </div>
        <input type="hidden" name="on1" value="Notes:">
        <div class="form-group">
          <label>Notes: </label>
          <input type="text" name="os1" maxlength="200" class="form-control">
        </div>
        <input type="hidden" name="currency_code" value="USD">
        <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
        <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
        <div class="form-group">
          <h4>You will be redirected to Paypal website.</h4>
          <h2>Than You!</h2>
        </div>
    </form>
  </div>
</div>




app/views/scripts/edit.html.erb
<%= render 'form' %>


app/views/scripts/index.html.erb
<div class="row">
  <div class="col-lg-4 pull-left" style="padding-bottom:5px">
    <%= link_to (t('projects.create_new')), new_script_path, class: "btn btn-success myshadow" %>
  </div>

  <%= form_tag scripts_path, :method => 'get' do %>
    <div class="col-lg-3 pull-right" style="padding-bottom:5px">
      <div class="input-group myshadow">
        <%= text_field_tag :searchdescr, params[:searchdescr], placeholder: (t('projects.search_description')), class: "form-control" %>
        <span class="input-group-btn">
          <button class="btn btn-warning" type="submit"><%= t('projects.go') %></button>
        </span>
      </div>
    </div>
  <% end %>
  <%= form_tag scripts_path, :method => 'get' do %>
    <div class="col-lg-3 pull-right" style="padding-bottom:5px">
      <div class="input-group myshadow">
        <%= text_field_tag :searchproject, params[:searchproject], placeholder: (t('projects.search_project')), class: "form-control" %>
        <span class="input-group-btn">
          <button class="btn btn-warning" type="submit"><%= t('projects.go') %></button>
        </span>
      </div>
    </div>
  <% end %>
</div>
<br>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><%= t('projects.my_projects') %></div>
  <!-- Table -->
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th><%= t('projects.name') %></th>
        <th><%= t('projects.description') %></th>
        <th><center><%= t('projects.action') %></center></th>
      </tr>
    </thead>
    <tbody>
      <% @scripts.each do |script| %>
        <tr>
          <td width=30%>
            <% @projstatuses.each do |s| %>
              <div>
                <% if s.id == script.status %>
                  <b><span style="color:<%= s.color %>"><%= s.statusname %></span></b>
                <% end %>
              </div>
            <% end %>
            <% if current_user.try(:admin?) %>
              <%= script.user.email %>
              <br>
            <% end %>
            <%= script.created_at.strftime('%m/%d/%Y') %>
          </td>
          <td width=50%><b><%= script.project %></b><br>
            <%= script.notes %></td>
          <td width=20% style="text-align:center" >
            <div class="btn-group btn-group-sm">
              <%= link_to (t('projects.view')), script_path(script), class: "btn btn-warning" %>              
              <%= link_to (t('projects.edit')), edit_script_path(script), class: "btn btn-success" %>
              <%= link_to (t('projects.delete')), script, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/scripts/new.html.erb
<div class="col-md-12">
	<h3>New Script</h3>
</div>

<%= render 'form' %>


app/views/scripts/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong><%= t('proj_view.notes') %></strong>
  <%= @script.notes %>
</p>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><%= t('proj_view.project') %> <strong><%= @script.project %></strong></div>
  <!-- Table -->
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th><%= t('proj_view.step_name') %></th>
        <th><%= t('projects.description') %></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td width=30%><strong><%= t('proj_edit.step1') %></strong></td>
        <td width=80%><%= @script.step1 %></td>
      </tr>
      <tr>
        <td width=30%><strong><%= t('proj_edit.step2') %></strong></td>
        <td width=80%><%= @script.step2 %></td>
      </tr>
      <tr>
        <td width=30%><strong><%= t('proj_edit.step3') %></strong></td>
        <td width=80%><%= @script.step3 %></td>
      </tr>
      <tr>
        <td width=30%><strong><%= t('proj_edit.step4') %></strong></td>
        <td width=80%><%= @script.step4 %></td>
      </tr>
      <tr>
        <td width=30%><strong><%= t('proj_edit.step5') %></strong></td>
        <td width=80%><%= @script.step5 %></td>
      </tr>
    </tbody>
  </table>
</div>
<div class="btn-group btn-group-sm">
  <%= link_to (t('projects.edit')), edit_script_path(@script), class: "btn btn-success" %>
  <%= link_to (t('site.back')), scripts_path, class: "btn btn-default" %>
</div>
