config/routes.rb
Czanitech::Application.routes.draw do
  resources :myimages do
    get 'show_hidden', :on => :collection
    get 'show_all', :on => :collection
  end

  resources :pymtreceiveds

  resources :pymts

  get "price/index"
  
  resources :projstatuses

  resources :customerchats

  get "allusers", to: 'users#index', as: :allusers
  get "edituser", to: "users#edit", as: :edituser

  resources :movielinks

  resources :sendmessages
  get 'send', to: 'sendmessages#new', as: :send
  get "about/index"
  get "home/index"
  
  resources :scripts

  devise_for :users
  
  devise_scope :user do
      get 'register', to: 'devise/registrations#new', as: :register
      get 'login', to: 'devise/sessions#new', as: :login
      get 'logout', to: 'devise/sessions#destroy', as: :logout
      get 'edit', to: 'devise/registrations#edit', as: :edit
  end

  root :to => "home#index"
  
  







  

end

app/models/customerchat.rb
class Customerchat < ActiveRecord::Base
	belongs_to :scripts
end

app/models/movielink.rb
class Movielink < ActiveRecord::Base

end

app/models/myimage.rb
class Myimage < ActiveRecord::Base
	belongs_to :user
	mount_uploader :image, ImageUploader
end

app/models/projstatus.rb
class Projstatus < ActiveRecord::Base

end

app/models/pymt.rb
class Pymt < ActiveRecord::Base
end

app/models/pymtreceived.rb
class Pymtreceived < ActiveRecord::Base
end

app/models/script.rb
class Script < ActiveRecord::Base

	before_save :concatenate_chat
	belongs_to :user

	def concatenate_chat
		if chat_entry_changed?
		    self.chat_history = "#{usertype} #{chat_entry}<hr>#{chat_history}".html_safe
		    self.chat_entry = ""
		end
	end

	def self.searchproject(search)
		if search
			find(:all, :conditions => ['LOWER(project) LIKE ?', "%#{search.downcase}%"], :order => "created_at DESC")
		else
			find(:all, :order => "created_at DESC")
		end
	end

	def self.searchdescr(search)
		if search
			find(:all, :conditions => ['LOWER(notes) LIKE ?', "%#{search.downcase}%"], :order => "created_at DESC")
		else
			find(:all, :order => "created_at DESC")
		end
	end
	
end

app/models/sendmessage.rb
class Sendmessage < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :scripts
  has_many :myimages

  def full_name 
  	first_name + " " + last_name
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projstatuses_controller.rb
class ProjstatusesController < ApplicationController
  before_action :set_projstatus, only: [:show, :edit, :update, :destroy]
  before_action :check_adm
  # GET /projstatuses
  # GET /projstatuses.json
  def index
    @projstatuses = Projstatus.all.order('ordertoshow')
  end

  # GET /projstatuses/1
  # GET /projstatuses/1.json
  def show
  end

  # GET /projstatuses/new
  def new
    @projstatus = Projstatus.new
  end

  # GET /projstatuses/1/edit
  def edit
  end

  # POST /projstatuses
  # POST /projstatuses.json
  def create
    @projstatus = Projstatus.new(projstatus_params)

    respond_to do |format|
      if @projstatus.save
        format.html { redirect_to @projstatus, notice: 'Projstatus was successfully created.' }
        format.json { render action: 'show', status: :created, location: @projstatus }
      else
        format.html { render action: 'new' }
        format.json { render json: @projstatus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projstatuses/1
  # PATCH/PUT /projstatuses/1.json
  def update
    respond_to do |format|
      if @projstatus.update(projstatus_params)
        format.html { redirect_to @projstatus, notice: 'Projstatus was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @projstatus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projstatuses/1
  # DELETE /projstatuses/1.json
  def destroy
    @projstatus.destroy
    respond_to do |format|
      format.html { redirect_to projstatuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projstatus
      @projstatus = Projstatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projstatus_params
      params.require(:projstatus).permit(:statusname, :ordertoshow, :color)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(type)
		case type
		when :alert
			"alert-error"
		when :notice
			"alert-success"
		else
			"alert-success"
		end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movielinks_helper.rb
module MovielinksHelper
end

app/helpers/myimages_helper.rb
module MyimagesHelper
end

app/helpers/price_helper.rb
module PriceHelper
end

app/helpers/projstatuses_helper.rb
module ProjstatusesHelper
end

app/helpers/pymts_helper.rb
module PymtsHelper
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/helpers/sendmessages_helper.rb
module SendmessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/projstatuses/_form.html.erb
<%= form_for(@projstatus) do |f| %>
  <% if @projstatus.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@projstatus.errors.count, "error") %> prohibited this projstatus from being saved:</h2>

      <ul>
      <% @projstatus.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading"><center><b>Edit Status</b></center></div>
      <div class="panel-body">
        <div class="col-md-2">
          <div class="field">
            <%= f.label :ordertoshow, "Show Order" %><br>
            <%= f.text_field :ordertoshow, :autofocus => true, class: "form-control", :required => true %>
          </div>
        </div>
        <div class="col-md-7">
          <div class="field">
            <%= f.label :statusname, "Status Name - " %>
            <i>Choose a Color:</i>
            <%= f.select :color, [['Red'], ['Blue'], ['Green'], ['Orange'], ['Black']], :prompt => "Choose a Color" %><br>
            <%= f.text_field :statusname, class: "form-control", :required => true %>
          </div>
        </div>
        <div class="col-md-3"><center>
          <div class="actions">
            <%= f.label  "Select Option" %><br>
            <%= f.submit "Submit", class: "btn btn-success" %>
            <%= link_to "Cancel", projstatuses_path, class: "btn btn-danger" %>
          </div></center>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/projstatuses/edit.html.erb
<%= render 'form' %>

app/views/projstatuses/index.html.erb
<%= link_to 'Add New Status', new_projstatus_path, class: "btn btn-success" %>
<br><br>
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Statuses</div>
  <!-- Table -->
  <table class="table table-striped table-bordered">

    <thead>
      <tr>
        <th>Show Order</th>
        <th>Status Name</th>
        <th><center>Action</center></th>
      </tr>
    </thead>

    <tbody>
      <% @projstatuses.each do |projstatus| %>
        <tr>
          <td width=10%><%= projstatus.ordertoshow %></td>
          <td width=70% style="color:<%= projstatus.color %>"><%= projstatus.statusname %></td>
          <td width=20% style="text-align:center" >
            <div class="btn-group btn-group-sm">
              <%= link_to 'Edit', edit_projstatus_path(projstatus), class: "btn btn-success" %>
              <%= link_to ' Delete', projstatus, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            </div>
          </td>
        </tr>

      <% end %>
    </tbody>
  </table>

<br>

app/views/projstatuses/new.html.erb
<%= render 'form' %>


app/views/projstatuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Statusname:</strong>
  <%= @projstatus.statusname %>
</p>

<%= link_to 'Edit', edit_projstatus_path(@projstatus) %> |
<%= link_to 'Back', projstatuses_path %>