config/routes.rb
Czanitech::Application.routes.draw do
  resources :myimages do
    get 'show_hidden', :on => :collection
    get 'show_all', :on => :collection
  end

  resources :pymtreceiveds

  resources :pymts

  get "price/index"
  
  resources :projstatuses

  resources :customerchats

  get "allusers", to: 'users#index', as: :allusers
  get "edituser", to: "users#edit", as: :edituser

  resources :movielinks

  resources :sendmessages
  get 'send', to: 'sendmessages#new', as: :send
  get "about/index"
  get "home/index"
  
  resources :scripts

  devise_for :users
  
  devise_scope :user do
      get 'register', to: 'devise/registrations#new', as: :register
      get 'login', to: 'devise/sessions#new', as: :login
      get 'logout', to: 'devise/sessions#destroy', as: :logout
      get 'edit', to: 'devise/registrations#edit', as: :edit
  end

  root :to => "home#index"
  
  







  

end

app/models/customerchat.rb
class Customerchat < ActiveRecord::Base
	belongs_to :scripts
end

app/models/movielink.rb
class Movielink < ActiveRecord::Base

end

app/models/myimage.rb
class Myimage < ActiveRecord::Base
	belongs_to :user
	mount_uploader :image, ImageUploader
end

app/models/projstatus.rb
class Projstatus < ActiveRecord::Base

end

app/models/pymt.rb
class Pymt < ActiveRecord::Base
end

app/models/pymtreceived.rb
class Pymtreceived < ActiveRecord::Base
end

app/models/script.rb
class Script < ActiveRecord::Base

	before_save :concatenate_chat
	belongs_to :user

	def concatenate_chat
		if chat_entry_changed?
		    self.chat_history = "#{usertype} #{chat_entry}<hr>#{chat_history}".html_safe
		    self.chat_entry = ""
		end
	end

	def self.searchproject(search)
		if search
			find(:all, :conditions => ['LOWER(project) LIKE ?', "%#{search.downcase}%"], :order => "created_at DESC")
		else
			find(:all, :order => "created_at DESC")
		end
	end

	def self.searchdescr(search)
		if search
			find(:all, :conditions => ['LOWER(notes) LIKE ?', "%#{search.downcase}%"], :order => "created_at DESC")
		else
			find(:all, :order => "created_at DESC")
		end
	end
	
end

app/models/sendmessage.rb
class Sendmessage < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :scripts
  has_many :myimages

  def full_name 
  	first_name + " " + last_name
  end
  
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/myimages_controller.rb
class MyimagesController < ApplicationController

  before_action :set_myimage, only: [:show, :edit, :update, :destroy]

  # GET /myimages
  # GET /myimages.json
  def index
    if current_user.admin?
      @myimages = Myimage.where(image_hidden: [false, nil])
    else
      @myimages = current_user.myimages.where(image_hidden: [false, nil])
    end 
  end

  def show_hidden
    if current_user.admin?
      @myimages = Myimage.where(image_hidden: [true, nil])
    else
      @myimages = current_user.myimages.where(image_hidden: [true, nil])
    end
    render 'index'
  end 

  def show_all
    if current_user.admin?
      @myimages = Myimage.all
    else
      @myimages = current_user.myimages.all
    end
    render 'index'
  end 

  # GET /myimages/1
  # GET /myimages/1.json
  def show
  end

  # GET /myimages/new
  def new
    @myimage = Myimage.new
  end

  # GET /myimages/1/edit
  def edit
  end

  # POST /myimages
  # POST /myimages.json
  def create
    @myimage = Myimage.new(myimage_params)

    respond_to do |format|
      if @myimage.save
        format.html { redirect_to @myimage, notice: 'Myimage was successfully created.' }
        format.json { render action: 'show', status: :created, location: @myimage }
      else
        format.html { render action: 'new' }
        format.json { render json: @myimage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /myimages/1
  # PATCH/PUT /myimages/1.json
  def update
    respond_to do |format|
      if @myimage.update(myimage_params)
        format.html { redirect_to @myimage, notice: 'Myimage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @myimage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /myimages/1
  # DELETE /myimages/1.json
  def destroy
    @myimage.destroy
    respond_to do |format|
      format.html { redirect_to myimages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_myimage
      @myimage = Myimage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def myimage_params
      params.require(:myimage).permit(:image_name, :image_link, :image, :user_id, :image_hidden)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(type)
		case type
		when :alert
			"alert-error"
		when :notice
			"alert-success"
		else
			"alert-success"
		end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movielinks_helper.rb
module MovielinksHelper
end

app/helpers/myimages_helper.rb
module MyimagesHelper
end

app/helpers/price_helper.rb
module PriceHelper
end

app/helpers/projstatuses_helper.rb
module ProjstatusesHelper
end

app/helpers/pymts_helper.rb
module PymtsHelper
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/helpers/sendmessages_helper.rb
module SendmessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/myimages/_form.html.erb
<%= form_for @myimage, html:{:multipart => true} do |f| %>

  <% if @myimage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@myimage.errors.count, "error") %> prohibited this myimage from being saved:</h2>

      <ul>
      <% @myimage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="col-md-4" style="float:none; margin:auto">
    <div class="panel panel-default">
      <div class="panel-heading"><center><%= t('proj_images.image_screen') %></center></div>
      <div class="panel-body">
        <div class="field">
          <%= f.file_field :image,  class: "form-control btn btn-warning" %>
        </div>
      </div>
      <div class="panel-body">
        <div class="field">
          <%= f.label :image_name, (t('proj_images.image_name')) %>
          <%= f.text_field :image_name, placeholder: (t('proj_images.image_name')),  class: "form-control", :required => true %><br>
        </div>
        <div class="field">
          <label><%= t('proj_images.hidde_this_image') %>
            <%= f.check_box :image_hidden %></label>
        </div>
      </div>
      <div class="panel-body">
        <div class="actions">
          <br>
          <%= f.submit (t('proj_images.accept_image')), disable_with: 'Uploading...', class: "btn btn-success" %>
          <%= link_to (t('proj_images.cancel')), myimages_path, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
  
<% end %>

app/views/myimages/edit.html.erb
<%= render 'form' %>

app/views/myimages/index.html.erb
<div class="col-md-12">

  <div class="btn-group btn-group-md col-md-7 row" style="padding-bottom:5px">
    <%= link_to (t('proj_images.add_new_image')), new_myimage_path, class: "btn btn-success myshadow" %>
  </div>
  <div class="btn-group btn-group-sm col-me-5 myshadow">
    <%= link_to (t('proj_images.all_images')), show_all_myimages_path, class: "btn btn-default" %>
    <%= link_to (t('proj_images.in_use')), myimages_path, class: "btn btn-default" %>
    <%= link_to (t('proj_images.hidden')), show_hidden_myimages_path, class: "btn btn-default" %>
  </div>

</div>

<br>

<div class="col-md-12 row">
  <% @myimages.each do |myimage| %>
    <center>
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <center><%= myimage.image_name %> - <%= myimage.id %></center>
          </div>
          <div class="panel-body">
            <div class="field">
              <div class="btn-group btn-group-sm">
                <%= link_to (t('proj_images.change_image')), edit_myimage_path(myimage), class: "btn btn-success" %>
                <%= link_to (t('proj_images.delete')), myimage, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
              </div><br><br>
              <div>
                <%= image_tag myimage.image_url(:thumb).to_s %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </center>
    <div id="openImage" class="modalDialog">
      <div>
        <a href="#close" title="Close" class="close">X</a>
        <%= image_tag myimage.image_url(:thumb).to_s %>
      </div>
    </div>
  <% end %>
</div>

app/views/myimages/new.html.erb
<%= render 'form' %>

app/views/myimages/show.html.erb
 <div class="col-md-4" style="float:none; margin:auto">
	<div class="panel panel-default">
		<div class="panel-heading"> 
			<strong>Image</strong>
		</div>
		<br>
		<div class="panel-body">
			<div> 
				Image Name: <strong><%= @myimage.image_name %></strong>
			</div>
		</div>
		<div class="panel-body">
			<div class="btn-group btn-group-sm">
			  <%= link_to ' Back to Images', myimages_path, class: "btn btn-warning" %>
			  <%= link_to 'Change Image', edit_myimage_path(@myimage), class: "btn btn-default" %>
			</div>
		</div>
		<br>
	</div>
</div>